include:
  - project: 'shared/gitlab-ci-includes'
    ref: main
    file:
      - '/base.yml'
      - '/pypi-packages.yml'
      - '/debian-packages.yml'
      - '/python.yml'

variables:
  APTLY_BASE_REPOSITORY: common

stages:
  - test
  - build
  - publish

unit test and feature test:
  stage: test
  image: python:3.11-bookworm
  script:
    - !reference [.add repositories, script]
    - ln -s .env.ci .env
    - addgroup --gid 1000 ci
    - adduser --disabled-password --gecos "" --uid 1000 --gid 1000 ci
    - pip install --no-cache-dir -r requirements/test.txt
    - pip install .
    - queue-support-migrate
    - pytest -n 10 -vvv --cov-branch --cov=cyberfusion.QueueSupport --cov-config=.coveragerc --cov-fail-under=100 --junitxml=report-pytest.xml --ci
  artifacts:
    reports:
      junit: report-*.xml
